/*
 * The MIT License
 *
 * Copyright 2021 Chilka Castro.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package simpleschoolsystem;

/**
 *
 * @author Chilka Castro
 */
public class HomeFrame extends javax.swing.JFrame {

    private User user;      // store the infor of the user that login

    /**
     * Creates new form homeFrame
     */
    public HomeFrame(User user) {
        initComponents();
        this.user = user;
        welcomeL.setText(String.format("Welcome %s", user.getUserName()));
        gradeP.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeL = new javax.swing.JLabel();
        displayB = new javax.swing.JButton();
        gradeP = new javax.swing.JPanel();
        grade1HL = new javax.swing.JLabel();
        grade2HL = new javax.swing.JLabel();
        grade3HL = new javax.swing.JLabel();
        grade4HL = new javax.swing.JLabel();
        grade5HL = new javax.swing.JLabel();
        grade1L = new javax.swing.JLabel();
        grade2L = new javax.swing.JLabel();
        grade3L = new javax.swing.JLabel();
        grade4L = new javax.swing.JLabel();
        grade5L = new javax.swing.JLabel();
        gradeFinalL = new javax.swing.JLabel();
        gradeFinalHL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeL.setText("Welcome,  ");

        displayB.setText("Display Grades");
        displayB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBActionPerformed(evt);
            }
        });

        grade1HL.setText("grade 1");

        grade2HL.setText("grade 2 ");

        grade3HL.setText("grade 3");

        grade4HL.setText("grade 4");

        grade5HL.setText("grade5");

        gradeFinalHL.setText("final grade");

        javax.swing.GroupLayout gradePLayout = new javax.swing.GroupLayout(gradeP);
        gradeP.setLayout(gradePLayout);
        gradePLayout.setHorizontalGroup(
            gradePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradePLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(gradePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradePLayout.createSequentialGroup()
                        .addComponent(grade1HL)
                        .addGap(18, 18, 18)
                        .addComponent(grade2HL)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradePLayout.createSequentialGroup()
                        .addComponent(grade1L, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(grade2L, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)))
                .addGap(11, 11, 11)
                .addGroup(gradePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grade3HL)
                    .addComponent(grade3L, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(gradePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grade4HL)
                    .addComponent(grade4L, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(gradePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(gradePLayout.createSequentialGroup()
                        .addComponent(grade5L, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(gradeFinalL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gradePLayout.createSequentialGroup()
                        .addComponent(grade5HL)
                        .addGap(34, 34, 34)
                        .addComponent(gradeFinalHL)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gradePLayout.setVerticalGroup(
            gradePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradePLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(gradePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(grade1HL)
                    .addComponent(grade2HL)
                    .addComponent(grade3HL)
                    .addComponent(grade4HL)
                    .addComponent(grade5HL)
                    .addComponent(gradeFinalHL))
                .addGap(18, 18, 18)
                .addGroup(gradePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grade1L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grade2L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grade3L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grade4L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grade5L, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gradeFinalL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcomeL)
                    .addComponent(gradeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(displayB)
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(welcomeL)
                .addGap(18, 18, 18)
                .addComponent(gradeP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(displayB)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void displayBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBActionPerformed
        if (user instanceof Student) {
            double[] grades;
            grades = ((Student) user).getGrades();
            grades = new double[]{78, 92, 99, 69, 88};
            grade1L.setText(grades[0] + "");
            grade2L.setText(grades[1] + "");
            grade3L.setText(grades[2] + "");
            grade4L.setText(grades[3] + "");
            grade5L.setText(grades[4] + "");

            gradeFinalL.setText(calcAvgGrade(grades) + "");
        }
//        else
//            ((Teacher) user);
    }//GEN-LAST:event_displayBActionPerformed

    /**
     * calculates the average of the grades
     *
     * @param grades the input grades
     * @return the average of the grades
     */
    public double calcAvgGrade(double[] grades) {
        double avg = 0;

        for (double grade : grades)
            avg += grade;

        return avg / grades.length;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton displayB;
    private javax.swing.JLabel grade1HL;
    private javax.swing.JLabel grade1L;
    private javax.swing.JLabel grade2HL;
    private javax.swing.JLabel grade2L;
    private javax.swing.JLabel grade3HL;
    private javax.swing.JLabel grade3L;
    private javax.swing.JLabel grade4HL;
    private javax.swing.JLabel grade4L;
    private javax.swing.JLabel grade5HL;
    private javax.swing.JLabel grade5L;
    private javax.swing.JLabel gradeFinalHL;
    private javax.swing.JLabel gradeFinalL;
    private javax.swing.JPanel gradeP;
    private javax.swing.JLabel welcomeL;
    // End of variables declaration//GEN-END:variables
}
