/*
 * The MIT License
 *
 * Copyright 2021 Chilka Castro.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package simpleschoolsystem;

import java.awt.Color;
import java.util.Random;
import javax.swing.ImageIcon;

/**
 * A simple class of LoginFrame
 * @author Chilka Castro
 */
public class LoginFrame extends javax.swing.JFrame {
    // CAN ALSO THE ICON AS DATA MEMBER
    
    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        
        // makes the panel appear invisible until it is clicked then it will show the panel
        signUpP.setVisible(false);   // hide the signUp panel
        ImageIcon titleImg1 = new ImageIcon("imgs\\user.png");                    // create the img object
        ImageIcon titleImg2 = new ImageIcon("imgs\\user.png");                    // create the img object
        ImageIcon titleImg3 = new ImageIcon("imgs\\user.png");                    // create the img object
        ImageIcon titleImg4 = new ImageIcon("imgs\\user.png");                    // create the img object
        
        ImageIcon[] iis = {titleImg1, titleImg2, titleImg3, titleImg4};
        imgL.setIcon(iis[new Random().nextInt(iis.length)]);
       
        SchoolSystem.intiData();     // initialize the user -> to LOAD ALL THE DATA
        //imgL.setIcon(titleImg1);      // add the image to the image label
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userL = new javax.swing.JLabel();
        passwordL = new javax.swing.JLabel();
        userTF = new javax.swing.JTextField();
        passwordTF = new javax.swing.JTextField();
        loginB = new javax.swing.JButton();
        signUpB = new javax.swing.JButton();
        titleL = new javax.swing.JLabel();
        signUpP = new javax.swing.JPanel();
        usernameL = new javax.swing.JLabel();
        passwordSignUpL = new javax.swing.JLabel();
        fnameL = new javax.swing.JLabel();
        lnameL = new javax.swing.JLabel();
        passwordSignUpTF = new javax.swing.JTextField();
        fnameTF = new javax.swing.JTextField();
        lnameTF = new javax.swing.JTextField();
        usernameTF = new javax.swing.JTextField();
        submitB = new javax.swing.JButton();
        loginMessageL = new javax.swing.JLabel();
        signUpMessageL = new javax.swing.JLabel();
        imgL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userL.setText("User :");

        passwordL.setText("Password :");

        loginB.setText("Login");
        loginB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBActionPerformed(evt);
            }
        });

        signUpB.setText("Sign Up");
        signUpB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpBActionPerformed(evt);
            }
        });

        titleL.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 24)); // NOI18N
        titleL.setText("Simple School System");

        signUpP.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        usernameL.setText("username :");
        usernameL.setToolTipText("");
        usernameL.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        passwordSignUpL.setText("password :");

        fnameL.setText("first name :");

        lnameL.setText("last name :");

        submitB.setText("Submit");
        submitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signUpPLayout = new javax.swing.GroupLayout(signUpP);
        signUpP.setLayout(signUpPLayout);
        signUpPLayout.setHorizontalGroup(
            signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpPLayout.createSequentialGroup()
                        .addGroup(signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(signUpPLayout.createSequentialGroup()
                                .addComponent(usernameL)
                                .addGap(26, 26, 26)
                                .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(signUpPLayout.createSequentialGroup()
                                .addComponent(passwordSignUpL)
                                .addGap(27, 27, 27)
                                .addComponent(passwordSignUpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(signUpPLayout.createSequentialGroup()
                                .addComponent(fnameL)
                                .addGap(26, 26, 26)
                                .addComponent(fnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(181, Short.MAX_VALUE))
                    .addGroup(signUpPLayout.createSequentialGroup()
                        .addComponent(lnameL)
                        .addGap(28, 28, 28)
                        .addComponent(lnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitB)
                        .addGap(17, 17, 17))))
        );
        signUpPLayout.setVerticalGroup(
            signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(usernameL)
                    .addComponent(usernameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordSignUpL)
                    .addComponent(passwordSignUpTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameL))
                .addGroup(signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpPLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(signUpPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lnameL)
                            .addComponent(lnameTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(submitB)
                        .addGap(15, 15, 15))))
        );

        signUpMessageL.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(signUpP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(loginMessageL, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(titleL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(imgL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(userL)
                                    .addComponent(passwordL))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(loginB, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(signUpB))
                                        .addGap(40, 40, 40))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(signUpMessageL, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(titleL))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(imgL, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(userL)
                            .addComponent(signUpB)
                            .addComponent(userTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(passwordL)
                        .addComponent(passwordTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loginB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginMessageL, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUpP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(signUpMessageL, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**EVENT HANDLER THAT WILL DO ACTIONS WHEN SUBMIT IS CLICKED
     * When submit button is clicked then it will take the input information
     * @param evt the event
     */
    private void submitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBActionPerformed
        // Step 1 : for  the sign up
        String userName = usernameTF.getText();
        String password = passwordTF.getName();
        String fname = fnameTF.getText();
        String lname = lnameTF.getText();
        
        User user;
        // Step 2: Create user
        // if the userName starts with s, then it is a student
        // if the userName starts with t, then it is a teacher
        if (userName.charAt(0) == 's')
            user  = new Student(userName, password, fname, lname);
//        else if (userName.charAt(0) == 't')
//            user = new 
        else {
            signUpMessageL.setForeground(Color.RED);
            signUpMessageL.setText("The syntax of the username is incorrect");
            return;
        }
        
        // Step 3: Check the system if the Users arraylist in the schoolsystem contains this user you just created above
        if (SchoolSystem.users.contains(user)) {
            // print an error message
            signUpMessageL.setForeground(Color.RED);
            signUpMessageL.setText("The user name is used, please change another one");
        }
        else { // if not then add this user and then serialize the data(store it externally)
            SchoolSystem.users.add(user); 
            SchoolSystem.serializeData("users.ser", SchoolSystem.users);
            signUpMessageL.setForeground(Color.GREEN);
            signUpMessageL.setText("New user generated successfully");
        }
    }//GEN-LAST:event_submitBActionPerformed

    /**
     * Set the sign up panel visible if sign up button is clicked
     * @param evt 
     */
    private void signUpBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpBActionPerformed
       signUpP.setVisible(true);
       // focus on the user name textfield in the sign up panel
       usernameTF.requestFocus(); // blue box pops up
    }//GEN-LAST:event_signUpBActionPerformed

    private void loginBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBActionPerformed
        String inputUserName = userTF.getText();
        String password = passwordTF.getText();

        for (User existUser : SchoolSystem.users) 
            if (existUser.getUserName().equals(inputUserName)
                    && existUser.getPassword().equals(password)) {
                // valid, jump to the new frame which contains the user's infor
                new HomeFrame(existUser).setVisible(true);
                this.setVisible(false);
                return;
            }

        loginMessageL.setText("Your account or password is not correct");
    }//GEN-LAST:event_loginBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fnameL;
    private javax.swing.JTextField fnameTF;
    private javax.swing.JLabel imgL;
    private javax.swing.JLabel lnameL;
    private javax.swing.JTextField lnameTF;
    private javax.swing.JButton loginB;
    private javax.swing.JLabel loginMessageL;
    private javax.swing.JLabel passwordL;
    private javax.swing.JLabel passwordSignUpL;
    private javax.swing.JTextField passwordSignUpTF;
    private javax.swing.JTextField passwordTF;
    private javax.swing.JButton signUpB;
    private javax.swing.JLabel signUpMessageL;
    private javax.swing.JPanel signUpP;
    private javax.swing.JButton submitB;
    private javax.swing.JLabel titleL;
    private javax.swing.JLabel userL;
    private javax.swing.JTextField userTF;
    private javax.swing.JLabel usernameL;
    private javax.swing.JTextField usernameTF;
    // End of variables declaration//GEN-END:variables
}
